name Continous Deployment workflow

on:
  push:
    branches:
      - master
jobs:
  cd:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
      - name: Git config
        run: |
          git config --global user.email "cd-user@my-app.com"
          git config --global user.name "cd-user"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy -- -r git@github.com:<owner>/<repository-name>.git
